### ISSUE TITLE
Use to access programmable logic on a FPGA using a soft-core

### ISSUE THREAD

**Issue by jhugon** [jhugon/ascii-serial-com#55]
Communicate with a NeoRV32 core that then maps registers to pulse counters in the programmable logic.

- [x] jhugon/ascii-serial-com-c#5
- [x] Do a character loopback test
- [x] Connect ASC and GPIO
  - [x] jhugon/vhdl_libs#31
  - [x] jhugon/ascii-serial-com-c#6
- [x] Connect the core with Wishbone pulse counter and test
  - [x] jhugon/vhdl_libs#29
  - [x] jhugon/ascii-serial-com-c#8
  - [x] jhugon/vhdl_libs#30
- [ ] Make c-firmware part of ROM
